name: Pull Request Template
description: Template for creating pull requests
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Please fill out the sections below to help us review your pull request.

  - type: textarea
    id: description
    attributes:
      label: "🚀 Description"
      description: "Please describe your changes in detail"
      placeholder: "Describe what changes you made and why..."
    validations:
      required: true

  - type: input
    id: related_issue
    attributes:
      label: "🧩 Related Issue"
      description: "Link to the related issue (if applicable)"
      placeholder: "Closes #123"

  - type: checkboxes
    id: change_type
    attributes:
      label: "📝 Type of Change"
      description: "What type of change does this PR introduce?"
      options:
        - label: "Bug fix 🐞"
        - label: "New feature ✨"
        - label: "Documentation update 📚"
        - label: "Refactor 🔨"
        - label: "Other (please describe in additional context)"

  - type: textarea
    id: testing
    attributes:
      label: "🧪 How Has This Been Tested?"
      description: "Please describe the tests that you ran to verify your changes"
      placeholder: "Describe your testing approach..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "📋 Checklist"
      description: "Please check all applicable items"
      options:
        - label: "My code follows the style guidelines of this project"
        - label: "I have performed a self-review of my code"
        - label: "I have commented my code, particularly in hard-to-understand areas"
        - label: "I have made corresponding changes to the documentation"
        - label: "My changes generate no new warnings"
        - label: "I have added tests that prove my fix is effective or that my feature works"
        - label: "New and existing unit tests pass locally with my changes"

  - type: textarea
    id: additional_context
    attributes:
      label: "📎 Additional Context"
      description: "Add any other context or screenshots about the PR here"
      placeholder: "Any additional information, screenshots, or context...."
