apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-temanwisata
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teman-wisata
  template:
    metadata:
      labels:
        app: teman-wisata
    spec:
      containers:
        - name: teman-wisata
          image: app-temanwisata:v1   # image hasil build nerdctl
          imagePullPolicy: Never
          ports:
            - containerPort: 8000      # sesuaikan dengan expose port di Dockerfile
          # kamu bisa comment env jika model belum tersedia
          env:
          #   - name: MODEL_URI
          #     value: ""
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: url
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: api_key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rand-secret
                  key: SECRET_KEY
            # Env non-sensitif langsung
            - name: ENVIRONMENT
              value: "prod"
            - name: ALGORITHM
              value: "HS256"
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-fastapi
  namespace: backend
spec:
  selector:
    app: teman-wisata
  ports:
    - port: 80
      targetPort: 8000
