apiVersion: v1
data:
  SECRET_KEY: Yzc3YmRhYThjMDAzZTg5N2M5Mjg5NjZiMjE2MjlmYjA0MDA2NTE3YzRmZmRjYTNmMGQ0MGU0YjA2Y2E4OGVhNg==
kind: Secret
metadata:
  creationTimestamp: null
  name: rand-secret
  namespace: backend
