alertmanager:
  enabled: false
grafana:
  enabled: false
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
    retention: 1d
    scrapeInterval: 1m
  service:
    type: ClusterIP
