name: build-image

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Tentukan TAG
        run: |
          BASE_TAG="${GITHUB_REF_NAME}"
          UNIQUE_SUFFIX=$(date +%Y%m%d%H%M%S)
          TAG="${BASE_TAG}-${UNIQUE_SUFFIX}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "Tag yang akan dipakai: ${TAG}"

      - name: SSH & Build image di VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            sudo nerdctl --address /run/k3s/containerd/containerd.sock \
              build -t app-temanwisata:${{ env.TAG }} -f deployment/docker/Dockerfile --namespace k8s.io .

      - name: Upload TAG sebagai artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: |
            <<< "${{ env.TAG }}" > image-tag.txt
            image-tag.txt
