name: build-image

on:
  release:
    types: [published]   # Trigger otomatis saat ada release di main
  workflow_dispatch: {}   # Bisa juga dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Tentukan TAG
        run: |
          # Gunakan tag release
          TAG="${GITHUB_REF_NAME}"
          echo "TAG=${TAG}" > $GITHUB_ENV
          echo "Tag yang akan dipakai: ${TAG}"

      - name: SSH & Build image di VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VM_PROJECT_PATH }}/deployment/docker
            sudo nerdctl --address /run/k3s/containerd/containerd.sock \
              build -t app-temanwisata:${{ env.TAG }} -f Dockerfile --namespace k8s.io .
            echo "${{ env.TAG }}" > ${{ secrets.VM_PROJECT_PATH }}/.image-tag

