name: Simple SSH test

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to VM and create hello.txt
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "Hello from GitHub Actions at $(date)" > hello.txt
            cat hello.txt
