name: Version Update

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  version_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Version Release
        uses: python-semantic-release/python-semantic-release@v10.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: true
          verbosity: 2
